"""
app.py
======
Gradio web interface for the Unofficial Guide RAG system.

Run with:
    python app.py

Then open: http://localhost:7860

Requires:
    pip install gradio groq chromadb sentence-transformers python-dotenv
"""

from __future__ import annotations
import gradio as gr
from query import ask

import os
import sys
from pathlib import Path
from typing import TypedDict
import chromadb
from chromadb.utils.embedding_functions import SentenceTransformerEmbeddingFunction
from dotenv import load_dotenv


# ---------------------------------------------------------------------------
# Handler — called by Gradio on every button click / Enter keypress
# ---------------------------------------------------------------------------

def handle_query(question: str) -> tuple[str, str, str]:
    """
    Wraps ask() and formats outputs for the three Gradio textboxes.

    Returns
    -------
    answer_text  : the grounded answer (or a grounding-failure message)
    sources_text : bullet list of source PDFs + page ranges
    status_text  : retrieval diagnostics shown in the status bar
    """
    if not question.strip():
        return "", "", "⚠️  Please enter a question."

    result = ask(question)

    # --- Answer ---
    answer_text = result["answer"]

    # --- Sources (programmatic — never from LLM) ---
    if result["sources"]:
        sources_text = "\n".join(f"• {s}" for s in result["sources"])
    else:
        sources_text = "No sources retrieved." if result["grounded"] else "No grounded sources."

    # --- Status line ---
    grounded_icon = "✅ Grounded" if result["grounded"] else "⚠️  Not grounded"
    status_text = (
        f"{grounded_icon}  |  "
        f"Chunks retrieved: {result['chunks_used']}  |  "
        f"Sources: {len(result['sources'])}"
    )

    return answer_text, sources_text, status_text


# ---------------------------------------------------------------------------
# Gradio UI
# ---------------------------------------------------------------------------

def build_ui() -> gr.Blocks:
    with gr.Blocks(
        title="The Unofficial Guide — Course RAG",
    ) as demo:

        # Header
        gr.Markdown(
            """
            # 📚 The Unofficial Guide
            ### AI/ML & Computer Vision Course Assistant
            Ask questions grounded in lecture notes from CAP5415, CAP6412, CAP6614,
            CAP5610, CAP5516, CAP6411, and more.

            > **Answers come only from the retrieved course materials.**
            > Sources are shown below every answer.
            """
        )

        # Input row
        with gr.Row():
            question_box = gr.Textbox(
                label="Your question",
                placeholder="e.g. What is self-attention and how does it work?",
                lines=2,
                scale=5,
            )

        ask_btn = gr.Button("Ask", variant="primary")

        # Status bar (compact, non-intrusive)
        status_box = gr.Textbox(
            label="Retrieval status",
            interactive=False,
            lines=1,
        )

        # Output row
        with gr.Row():
            answer_box = gr.Textbox(
                label="Answer",
                lines=12,
                scale=3,
                interactive=False,
            )
            sources_box = gr.Textbox(
                label="Retrieved from",
                lines=12,
                scale=1,
                interactive=False,
            )

        # Example questions — helps demo reviewers understand what to ask
        gr.Examples(
            examples=[
                ["What is self-attention and how does it work in transformers?"],
                ["How does an autoencoder differ from PCA for dimensionality reduction?"],
                ["What are the main applications of autoencoders in computer vision?"],
                ["What is positional encoding and why do transformers need it?"],
                ["What is the encoder-decoder architecture used for?"],
            ],
            inputs=question_box,
            label="Example questions — click to load",
        )

        # Footer
        gr.Markdown(
            """
            ---
            *Answers are grounded in retrieved lecture materials only.
            Sources are assembled from document metadata — not generated by the LLM.*
            """
        )

        # Wire up events
        outputs = [answer_box, sources_box, status_box]

        ask_btn.click(
            fn=handle_query,
            inputs=question_box,
            outputs=outputs,
        )
        question_box.submit(   # also fires on Enter key
            fn=handle_query,
            inputs=question_box,
            outputs=outputs,
        )

    return demo


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    demo = build_ui()
    demo.launch(
        server_name="127.0.0.1",  # Windows-compatible local address
        server_port=7860,
        share=False,              # set True to get a public gradio.live link
        show_error=True,
        theme=gr.themes.Soft(),
    )
